language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

before_script:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - nosetests --with-coverage tests/test-utils-globals.py tests/test-utils-console.py tests/test-utils-aws.py tests/test-utils-fs.py tests/test-utils-credentials.py tests/test-utils-conditions.py || 1

after success:
    - coveralls
