language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

before_script:
  - pip install -r requirements.txt
  - pip install coveralls

script:
    - nosetests --with-coverage tests/test-load_data.py tests/test-utils.py || exit 1

after_success:
    - coveralls
